### ISSUE TITLE
houdini link dead

### ISSUE THREAD

**Issue by letroll** [geeks-r-us/anbox-playstore-installer#13]

**Comment by letroll** [comment]
I have made a mirror from baidu link = https://mega.nz/#!iTY2yYKA!2A6xMgE1KoLxg2EoVM13rcPUcV4d4qvBIOS-XpsmaQM

**Comment by geeks-r-us** [comment]
Is there a way to get wget  to download from mega.nz?
With your link I only get the index.html

**Comment by letroll** [comment]
no sorry, I mirrored the link because to download the file. The only way I found was to download on the baidu's mirror link. But it requires an account, unfeasible in France ... But I was able to override with a chrome extension, which allows to obtain the download links without having to enter an account. Here is the Baidu link accessible with wget:
http://d.pcs.baidu.com/file/7ebf618b1af94a02322d9f2d2610090b?fid=4114050833-250528-969622490318383&dstime=1537692663&rt=sh&sign=FDtAERV-DCb740ccc5511e5e8fedcff06b081203-O8m7V6G5H3hlGdbjk63Ic%2FgYHaU%3D&expires=8h&chkv=1&chkbd=0&chkpc=&dp-logid=397774853265050574&dp-callid=0&shareid=3989420381&r=511462858

**Comment by geeks-r-us** [comment]
should work again
