### ISSUE TITLE
Version without snap/snapd?

### ISSUE THREAD

**Issue by xoitx** [geeks-r-us/anbox-playstore-installer#16]
Hi,
I was wondering if it's possible for a version without snap for those of us that like to build from source the normal way. That and also the aur packages have only the build version.
Is there a way to edit the script such that I can use it without snap?
Cause when I tried it, it said cannot find /snap ...
Regards

**Comment by LinArcX** [comment]
I install anbox through aur in arch Linux. How to use your scripts? (without snap)

**Comment by modo-j** [comment]
I'll rewrite the script to work with AUR/possibly source built version when I get home. 

Essentially, (mind you, I only looked it over for about ten seconds) you just have to change the directory for the android image to /var/lib/anbox/android.img and use systemctl restart instead of snap restart... That SHOULD be enough.

**Comment by Saren-Arterius** [comment]
https://gist.github.com/Saren-Arterius/ea10a323dd208a28b9463508af8343a4

Tested on Arch Linux with Anbox installation from AUR. This works by unsquashing the img, keep the routine and squashing into a new img. No overlayfs is used.

**Comment by Arucard1983** [comment]
I also made a version that works with the Debian Contrib repositories.

**Comment by timmyfromspace** [comment]
@Arucard1983 would you mind sharing it? I see your fork, but no changes, thank you :-)

**Comment by Arucard1983** [comment]
> @Arucard1983 would you mind sharing it? I see your fork, but no changes, thank you :-)

It's on "debian" branch of my fork.

https://github.com/Arucard1983/anbox-playstore-installer/tree/debian
