### ISSUE TITLE
android.img missing?

### ISSUE THREAD

**Issue by 7thCore** [geeks-r-us/anbox-playstore-installer#17]
Hello, im using arch linux but i installed anbox with snap and tried running your script and im getting the following error:

`user@Tempest ~]$ wget https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh
--2018-11-08 21:11:40--  https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 151.101.112.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.112.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7878 (7,7K) [text/plain]
Saving to: ‘install-playstore.sh’

install-playstore.sh       100%[==========]   7,69K  --.-KB/s    in 0s      

2018-11-08 21:11:40 (30,8 MB/s) - ‘install-playstore.sh’ saved [7878/7878]

[user@Tempest ~]$ chmod +x install-playstore.sh
[user@Tempest ~]$ sudo ./install-playstore.sh
Restarted.
/var/snap/anbox/common/rootfs-overlay
/home/user/anbox-work
cp: cannot stat '/snap/anbox/current/android.img': No such file or directory`

Edit: Nevermind, i downloaded an img from anbox manualy and it works.

**Comment by takov751** [comment]
I had the same problem and Archwiki gave me the answer:

`Classic snaps
Some snaps (e.g. Skype and Pycharm) use classic confinement. However, classic confinement requires the /snap directory, which is not FHS-compliant. Therefore, the snapd package doesn't ship this directory. However, if the user wants to, they can manually create a symlink from /snap to /var/lib/snapd/snap, to allow the installation of classic snaps:

# ln -s /var/lib/snapd/snap /snap`

Source : https://wiki.archlinux.org/index.php/Snap

**Comment by geeks-r-us** [comment]
Can also related to an old anbox-work (other permissions) directory. just delete anbox-work and retry.
