### ISSUE TITLE
Can't login to play store?

### ISSUE THREAD

**Issue by BobbyWibowo** [geeks-r-us/anbox-playstore-installer#26]
A fresh anbox `176` install with `open_gapps-x86_64-7.1-mini-20190625.zip`.
Pressing "SIGN IN" button in Play Store does pretty much nothing.
Doesn't seem like Play Store itself is freezing either.
Settings > Accounts > Add account does nothing too.
In fact it appears to crash Settings after a few moments.
I've tried purging user data `/var/snap/anbox/common/data` then restarted anbox, still the same issue.

It's a fresh install cause I had the same issue with an old install.
Play Store said I had to re-authorize, but couldn't, so I reinstalled anbox.

**Comment by BobbyWibowo** [comment]
Sigh, never mind. I had to look through some old tutorial-ish articles to remember that I had to enable all permissions for play services and play store. Can confirm it logged in just fine after that.

**Comment by mirzaatifbaig** [comment]
> Sigh, never mind. I had to look through some old tutorial-ish articles to remember that I had to enable all permissions for play services and play store. Can confirm it logged in just fine after that.

did You find any solution, stuck at the same thing
