### ISSUE TITLE
Add arm64-v8a to abilist and abilist64

### ISSUE THREAD

**Issue by 86423355844265459587182778** [geeks-r-us/anbox-playstore-installer#27]
Both scripts install the arm64 libraries and add houdini64 binfmt entries, but `arm64-v8a` is not added to `ro.product.cpu.abilist` and `ro.product.cpu.abilist64` in `build.prop`. Users may not be able to install APKs built for arm64.

**Comment by geeks-r-us** [comment]
done e1f71c6

**Comment by 86423355844265459587182778** [comment]
@geeks-r-us 
Thanks. `arm64-v8a` is added to `ARM_TYPE`, but `ARM_TYPE` is used in `ro.product.cpu.abilist32`. Since `arm64-v8a` is 64-bit, will this cause issues?
