### ISSUE TITLE
img mistype fix

### ISSUE THREAD

**Issue by ivan046** [geeks-r-us/anbox-playstore-installer#3]
https://github.com/geeks-r-us/anbox-playstore-installer/blob/master/install-playstore.sh#L221
Change, please
`$SUDO mv ./squashfs-root/android.img ./andorid.img-$NUMBER`
to
`$SUDO mv ./squashfs-root/android.img ./android.img-$NUMBER`

**Comment by geeks-r-us** [comment]
fixed with d6e8d6b9b2d302cca46a40c282b95d35e7a2c13c
