### ISSUE TITLE
OpenGApps version change silently stops installer script

### ISSUE THREAD

**Issue by cmor3** [geeks-r-us/anbox-playstore-installer#42]
The installer script sets up a variable for opengapps with the "mini" version specified. However, there is no mini version available on the opegapps sourceforge download site so the script fails silently. The two versions available are tvstock and pico. I replaced "mini" in the variable def to "pico" and the script finished successfully. I don't know if there are any "mini" files available, but I wasn't able to find any. This was in the x86_64 section, fwiw.

**Comment by Fanna1119** [comment]
I also realised this. I changed the url of the code to the following. (I found the URL for mini via https://opengapps.org/)

`OPENGAPPS_RELEASEDATE="20200127" 

OPENGAPPS_FILE="open_gapps-x86_64-7.1-mini-$OPENGAPPS_RELEASEDATE.zip"
OPENGAPPS_URL="https://tenet.dl.sourceforge.net/project/opengapps/x86_64/$OPENGAPPS_RELEASEDATE/$OPENGAPPS_FILE"`

**Comment by geeks-r-us** [comment]
fixed with #43
