### ISSUE TITLE
404: Not Found

### ISSUE THREAD

**Issue by miky2k** [geeks-r-us/anbox-playstore-installer#47]
Loading open gapps from https://sourceforge.net/projects/opengapps/files/x86_64/20200407/open_gapps-x86_64-7.1-pico-20200407.zip
--2020-04-09 18:17:53--  https://sourceforge.net/projects/opengapps/files/x86_64/20200407/open_gapps-x86_64-7.1-pico-20200407.zip
Risoluzione di sourceforge.net (sourceforge.net)... 216.105.38.13
Connessione a sourceforge.net (sourceforge.net)|216.105.38.13|:443... connesso.
Richiesta HTTP inviata, in attesa di risposta... 404 Not Found
2020-04-09 18:17:55 ERRORE 404: Not Found.

**Comment by miky2k** [comment]
Please remove -q on wget in next iteration , better debug in case of trouble.

**Comment by miky2k** [comment]
Workaround : 
download opengapps on anbox-work

**Comment by tommywatson** [comment]
> download opengapps on anbox-work

Can you please explain this?

**Comment by miky2k** [comment]
You can download manually open_gapps-x86_64-7.1-pico-20200407.zip and put in ./anbox-work directory and the script work.

**Comment by tommywatson** [comment]
Thanks!

**Comment by bdombro** [comment]
You could also change the value of OPENGAPPS_RELEASEDATE="20200407" in install-playstore.sh

**Comment by geeks-r-us** [comment]
Should be fixed with the last commits

**Comment by leestarb** [comment]
> You can download manually open_gapps-x86_64-7.1-pico-20200407.zip and put in ./anbox-work directory and the script work.

Thankx!
It's also important to remove several lines that doing the archive download. Without this it just stucks on "downloading ..."!
