### ISSUE TITLE
install-houdini-only.sh for non snap user?

### ISSUE THREAD

**Issue by miill1** [geeks-r-us/anbox-playstore-installer#52]
I would like to know how to change the code from "install-houdini-only.sh" to make it work without a snap installation?
I found some people (e.g Pull request User: Arucard1983) worked on a Debian non snap installer but unfortunately install-houdini-only.sh was removed.

I changed some Lines (accordingly to https://github.com/geeks-r-us/anbox-playstore-installer/pull/28/files) to make it work without snap but I failed.

Btw. I am aware the playstore-installer includes houdini (therefore it was removed, I guess) but I am not interested to install google playstore.

**Comment by Afsalmc** [comment]
https://github.com/Afsalmc/houdini-anbox/blob/main/install-houdini.sh

This is working
