### ISSUE TITLE
no such file or directory

### ISSUE THREAD

**Issue by nazthelizard122** [geeks-r-us/anbox-playstore-installer#54]
./install-playstore.sh: line 132: /etc/systemd/system/anbox-container-manager.service.d/override.conf: No such file or directory
when i go through the instalation i run the script and it comes back with this error

**Comment by nazthelizard122** [comment]
Fixed

**Comment by Santorz** [comment]
Please how did you go about it?

**Comment by NickWilde263** [comment]
i got same issue

**Comment by NickWilde263** [comment]
im not remember how i install anbox but sure im not install it with snap

**Comment by NickWilde263** [comment]
> Please how did you go about it?

i can help give some info

**Comment by 4joey1** [comment]
I also have same issue on Debian

**Comment by wajahatahmad** [comment]
please share the solution

**Comment by NickWilde263** [comment]
recreate the folder structure

**Comment by rithik2002** [comment]
> ./install-playstore.sh: line 132: /etc/systemd/system/anbox-container-manager.service.d/override.conf: No such file or directory
> when i go through the instalation i run the script and it comes back with this error

same issue
:(

**Comment by rithik2002** [comment]
> please share the solution

if you installed using snap then change line 155 path as snap.anbox.container-manager.service

**Comment by kahuria00** [comment]
./install-playstore.sh: line 155: /etc/systemd/system/snap.anbox.container-manager.service: Permission denied
how do I fix this it happened after I changed line 155

**Comment by mikakun18** [comment]
I found a simple solution.

First download the script to the current directory:
`wget https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh`

Open the script in your favorite text editor and find the text  _/etc/systemd/system/snap.anbox.container-manager.service_

Replace this with _/lib/systemd/system/anbox-container-manager.service_

Save the changes to the script. Then make to make it executable run in terminal:
`chmod +x install-playstore.sh`

Then run the script with:
`sudo ./install-playstore.sh`
(sudo is required in order to access the above directory)

Also I am running the debian variant of anbox (anbox 0.0~git20210106-1-Debian).

**Comment by 4joey1** [comment]
When I got error below

`install-playstore.sh: line 155: /etc/systemd/system/anbox-container-manager.service.d/override.conf: No such file or directory`

I followed the thread responses above and changed my line 155 from` $SUDO cat >/etc/systemd/system/snap.anbox.container-manager.service/override.conf<<EOF` to  `$SUDO cat >/lib/systemd/system/anbox-container-manager.service/override.conf<<EOF` and ran the script again but now got error below

`./install-playstore.sh: line 155: /lib/systemd/system/anbox-container-manager.service/override.conf: Not a directory`

I removed the override.conf line and when I ran the script again I now got the following message

```
/var/lib/anbox/rootfs-overlay
Overlay no enabled ! Please check error messages!
```
Please confirm if I have to remove the override.conf line and how doe I finally resolve my issue?

**Comment by hegdenischay** [comment]
as @NickWilde263 had rightly mentioned, the correct way to solve this is to recreate the folder structure, i.e. recreate the `/etc/systemd/system/anbox-container-manager.service.d/` folder and run the script as root.

changing `/etc/systemd/system/anbox-container-manager.service.d/override.conf` to `/lib/systemd/system/anbox-container-manager.service` overwrites the actual systemd service, which wouldn't be a good idea.

**Comment by englianhu** [comment]
> Edit: For some reason I lost internet connection in Anbox after doing this (the error was `Anbox bridge interface 'anbox0' doesn't exist`). I don't know if it was the script or the change that I made that caused it but I was able to fix it by following the steps on the accepted answer: [linux - Internet not working in Anbox on Ubuntu 18.04 - Super User](https://superuser.com/questions/1395384/internet-not-working-in-anbox-on-ubuntu-18-04). Also restart the container service again after doing these steps. But these steps for the network fix might not work for everyone, so I wouldn't recommend this solution until it can confirmed that the problem is caused by the script itself, not by the change made in the script.
> 
> I found a simple solution.
> 
> 1. First download the script to the current directory:
>    `wget https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh`
> 2. Open the script in your favorite text editor and find the text  _/etc/systemd/system/snap.anbox.container-manager.service_
> 3. Replace this with the path to the anbox container service. You can find it using `sudo systemctl status anbox-container-manager.service` or `sudo systemctl status snap.anbox.container-manager.service`. For me it is _/lib/systemd/system/anbox-container-manager.service_
> 4. Save the changes to the script. Then to make it executable run in terminal:
>    `chmod +x install-playstore.sh`
> 5. Then run the script with:
>    `sudo ./install-playstore.sh`
>    (sudo is required in order to access the above directory in step 3)
> 
> Also I am running the debian variant of anbox (anbox 0.0~git20210106-1-Debian).
> 
> Hope this helps.

```diff
+:~$ sudo systemctl status anbox-container-manager.service
● anbox-container-manager.service - Anbox Container Manager
     Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor pre>
    Drop-In: /etc/systemd/system/anbox-container-manager.service.d
             └─override.conf
+     Active: inactive (dead)
  Condition: start condition failed at Tue 2021-12-14 17:43:51 JST; 9min ago
             └─ ConditionPathExists=/var/lib/anbox/android.img was not met
       Docs: man:anbox(1)

Dec 14 04:35:48 Scibrokes-Trading systemd[1]: Condition check resulted in Anbox Container Man>
Dec 14 17:43:51 Scibrokes-Trading systemd[1]: Condition check resulted in Anbox Container Man>
+:~$ sudo micro /etc/systemd/system/snap.anbox.container-manager.service
+:~$ sudo systemctl status snap.anbox.container-manager.service
● snap.anbox.container-manager.service - Service for snap application anbox.container-manager
     Loaded: loaded (/etc/systemd/system/snap.anbox.container-manager.service; enabled; vendo>
+     Active: active (running) since Tue 2021-12-14 17:43:47 JST; 11min ago
   Main PID: 709052 (anbox)
      Tasks: 9 (limit: 18890)
     Memory: 4.8M
     CGroup: /system.slice/snap.anbox.container-manager.service
             └─709052 /snap/anbox/186/usr/bin/anbox container-manager --data-path=/var/snap/a>

Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:        initial>
Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:        transfe>
Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Successfully setup rootfs overlay
Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Mounting "/var/snap/anbox/common/cache" on ">
Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Mounting "/var/snap/anbox/common/data" on "/>
Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Everything setup. Waiting for incoming conne>
```

**Comment by FoxieFlakey** [comment]
> > Edit: For some reason I lost internet connection in Anbox after doing this (the error was `Anbox bridge interface 'anbox0' doesn't exist`). I don't know if it was the script or the change that I made that caused it but I was able to fix it by following the steps on the accepted answer: [linux - Internet not working in Anbox on Ubuntu 18.04 - Super User](https://superuser.com/questions/1395384/internet-not-working-in-anbox-on-ubuntu-18-04). Also restart the container service again after doing these steps. But these steps for the network fix might not work for everyone, so I wouldn't recommend this solution until it can confirmed that the problem is caused by the script itself, not by the change made in the script.
> > I found a simple solution.
> > 
> > 1. First download the script to the current directory:
> >    `wget https://raw.githubusercontent.com/geeks-r-us/anbox-playstore-installer/master/install-playstore.sh`
> > 2. Open the script in your favorite text editor and find the text  _/etc/systemd/system/snap.anbox.container-manager.service_
> > 3. Replace this with the path to the anbox container service. You can find it using `sudo systemctl status anbox-container-manager.service` or `sudo systemctl status snap.anbox.container-manager.service`. For me it is _/lib/systemd/system/anbox-container-manager.service_
> > 4. Save the changes to the script. Then to make it executable run in terminal:
> >    `chmod +x install-playstore.sh`
> > 5. Then run the script with:
> >    `sudo ./install-playstore.sh`
> >    (sudo is required in order to access the above directory in step 3)
> > 
> > Also I am running the debian variant of anbox (anbox 0.0~git20210106-1-Debian).
> > Hope this helps.
> 
> ```diff
> +:~$ sudo systemctl status anbox-container-manager.service
> ● anbox-container-manager.service - Anbox Container Manager
>      Loaded: loaded (/lib/systemd/system/anbox-container-manager.service; enabled; vendor pre>
>     Drop-In: /etc/systemd/system/anbox-container-manager.service.d
>              └─override.conf
> +     Active: inactive (dead)
>   Condition: start condition failed at Tue 2021-12-14 17:43:51 JST; 9min ago
>              └─ ConditionPathExists=/var/lib/anbox/android.img was not met
>        Docs: man:anbox(1)
> 
> Dec 14 04:35:48 Scibrokes-Trading systemd[1]: Condition check resulted in Anbox Container Man>
> Dec 14 17:43:51 Scibrokes-Trading systemd[1]: Condition check resulted in Anbox Container Man>
> +:~$ sudo micro /etc/systemd/system/snap.anbox.container-manager.service
> +:~$ sudo systemctl status snap.anbox.container-manager.service
> ● snap.anbox.container-manager.service - Service for snap application anbox.container-manager
>      Loaded: loaded (/etc/systemd/system/snap.anbox.container-manager.service; enabled; vendo>
> +     Active: active (running) since Tue 2021-12-14 17:43:47 JST; 11min ago
>    Main PID: 709052 (anbox)
>       Tasks: 9 (limit: 18890)
>      Memory: 4.8M
>      CGroup: /system.slice/snap.anbox.container-manager.service
>              └─709052 /snap/anbox/186/usr/bin/anbox container-manager --data-path=/var/snap/a>
> 
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:        initial>
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:        transfe>
> Dec 14 17:43:48 Scibrokes-Trading anbox.container-manager[709052]:     709052:
> Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Successfully setup rootfs overlay
> Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Mounting "/var/snap/anbox/common/cache" on ">
> Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Mounting "/var/snap/anbox/common/data" on "/>
> Dec 14 17:43:48 Scibrokes-Trading anbox[709052]: Everything setup. Waiting for incoming conne>
> ```

what this suppose to for? (is this additional information for the comment you are quoting?)
