### ISSUE TITLE
Play store freezes anbox

### ISSUE THREAD

**Issue by castlec** [geeks-r-us/anbox-playstore-installer#8]
I was able to run the script. Play store installs. I opened the app and logged in. Log was successful although it seemed to freeze up. It eventually closed. 

I am now logged in but when I try to load the play store to add applications, the play store window renders is non responsive. Additionally, the anbox manager becomes non responsive. 

A restart of the container brings everything back to life. 

This is on anbox beta, installed today, 2018-08-05

**Comment by BobbyWibowo** [comment]
I installed anbox and this script just today, and I can confirm that this occasionally happen with me too.

Play Store is already working just fine. I could confirm that my account was already logged in and I could login to other apps that had G+ login. I had also installed Firefox from it.

Anyways, for the time being I just use APKPure. To begin with, some of the apps that I want to use aren't available in Play Store anyways.

**Comment by geeks-r-us** [comment]
I updated to the newest GApps an its working  again 145.
