### ISSUE TITLE
unexpected e_machine: 40

### ISSUE THREAD

**Issue by castlec** [geeks-r-us/anbox-playstore-installer#9]
I'm not sure if this is because of houdini or because of an issue with the image.

`08-05 21:43:51.114  1288  1288 E ncaughtExceptionHandler: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.microsoft.office.lync15-1/lib/arm/libBreakpadLibrary.so" has unexpected e_machine: 40
08-05 21:43:51.114  1288  1288 E ncaughtExceptionHandler: 	at java.lang.Runtime.loadLibrary0(Runtime.java:989)
08-05 21:43:51.114  1288  1288 E ncaughtExceptionHandler: 	at java.lang.System.loadLibrary(System.java:1530)
08-05 21:43:51.114  1288  1288 E ncaughtExceptionHandler: 	at com.microsoft.breakpad.BreakpadWrapper.<clinit>(BreakpadWrapper.java:93)
08-05 21:43:51.114  1288  1288 E ncaughtExceptionHandler: 	at com.microsoft.breakpad.BreakpadWrapper.getInstance(BreakpadWrapper.java:50)
`

**Comment by geeks-r-us** [comment]
It's related to #10

**Comment by geeks-r-us** [comment]
see #10
